services:
  - type: web
    name: n8n-viral-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: GEMINI_API_KEY
        value: AIzaSyBSx0SUs7lsH1Q4mo90nW_s7zN5I4G51lU
      - key: N8N_WEBHOOK_URL
        value: https://learnaiwithakshay.app.n8n.cloud/webhook-test/webhook-test
      - key: FRONTEND_URL
        value: https://frontend-c28eezgnf-akshayseeken-9851s-projects.vercel.app
